### ISSUE TITLE
`Laser Turret Range Overlay` should be changed to `Turret Range Overlay` 

### ISSUE THREAD

**Issue by credomane** [justarandomgeek/factorio-palettecleanser#1]
`Laser Turret Range Overlay` should be changed to `Turret Range Overlay` in the locale since it affects the color of the range overlay for all turrets.

Gun, Laser and Flamethower turrets. Plus any modded turrets.

**Comment by justarandomgeek** [comment]
Good catch - I always forget non-laser turrets exist!

**Comment by credomane** [comment]
I gave the whole mod a once over. :)

Now I'm trying to locate the overlay color for miners/drills. Those are extremely hard to see with the new high-resolution resource graphics.

**Comment by justarandomgeek** [comment]
yeah, i wasn't sure which other overlays were worth doing - if you see others you think are, by all means hook them up!
