### ISSUE TITLE
Suggested Color Sets

### ISSUE THREAD

**Issue by justarandomgeek** [justarandomgeek/factorio-palettecleanser#2]
The default colors aim to be close to vanilla coloring, but obviously users will want varied settings. If you've got a good color set, please post it here!

I'll try and find a good way to provide presets in the future.

**Comment by Eepsquared** [comment]
Can you make (or do you know of) a mod to make the inserter pickup/drop indicators transparent?

**Comment by mark-c** [comment]
@Eepsquared What do you mean? If you mean regular arrows, you can turn them off in the game options.

**Comment by Eepsquared** [comment]
MORE transparent...
